import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
import WebSocket from 'ws';
process.env.RPG_CONNECT_GM_KEY='test-key-abcdefghijklmnopqrstuvwxyz';process.env.PORT='0';
const {server,wss}=await import('./rpg-connect-server.js');await new Promise(r=>server.listening?r():server.once('listening',r));
const url=`ws://127.0.0.1:${server.address().port}`;
const until=fn=>new Promise((resolve,reject)=>{let start=Date.now();const check=()=>fn()?resolve():Date.now()-start>2000?reject(Error('timeout')):setTimeout(check,10);check()});
const wait=(ws,type)=>new Promise((resolve,reject)=>{let timer=setTimeout(()=>reject(Error('timeout '+type)),2000);let fn=data=>{let m=JSON.parse(String(data));if(m.type!==type)return;clearTimeout(timer);ws.off('message',fn);resolve(m)};ws.on('message',fn)});
const send=(ws,m)=>ws.send(JSON.stringify({v:1,...m}));
test('ENCOUNTER reçoit l’état et route les dégâts au compagnon sans double mutation',async()=>{
 const dom=new JSDOM('<!doctype html><body><header class="topbar"></header></body>',{url:'https://biggie-mj.github.io/Table-de-jeu/',runScripts:'outside-only'});
 dom.window.WebSocket=WebSocket;Object.defineProperty(dom.window.crypto,'randomUUID',{value:()=>Math.random().toString(36).slice(2)});
 dom.window.eval(`window.state={ui:{mode:'prep'},encounter:{participants:[{id:'p1',name:'Samoth',kind:'player',hp:72,maxHp:72,tempHp:0,ac:14,initiative:0}],log:[],round:1,currentTurn:0,selectedId:null}};window.localDamage=0;window.saveState=()=>{};window.render=()=>{};window.log=()=>{};window.checkpoint=()=>{};window.sortedParticipants=()=>[...state.encounter.participants].sort((a,b)=>b.initiative-a.initiative);window.activeParticipant=()=>sortedParticipants()[state.encounter.currentTurn]||null;window.processStartTurn=()=>{};window.setMode=mode=>{state.ui.mode=mode};window.applyDamageMany=(ids,amount)=>{localDamage+=amount};window.applyHealMany=()=>{};window.applyDamageDirect=(target,amount)=>{localDamage+=amount;return{amount}};window.applyHealDirect=()=>{};window.actualAdvanceTurn=()=>{}`);
 dom.window.eval(readFileSync(new URL('./rpg-connect-mj.js',import.meta.url),'utf8'));
 dom.window.document.querySelector('#rpgMjEndpoint').value=url;dom.window.document.querySelector('#rpgMjKey').value=process.env.RPG_CONNECT_GM_KEY;dom.window.document.querySelector('#rpgMjConnect').click();await until(()=>dom.window.RPGConnectMJ.getStatus().connected);const room=dom.window.RPGConnectMJ.getStatus().room;
 dom.window.document.querySelector('[data-invite="samoth"]').click();await until(()=>!!dom.window.document.querySelector('.rpg-mj-token'));
 const token=dom.window.document.querySelector('.rpg-mj-token code').textContent;
 const player=new WebSocket(url);await new Promise(r=>player.once('open',r));let joined=wait(player,'welcome');send(player,{type:'hello',role:'player',room,characterId:'samoth',token});await joined;
 dom.window.RPGConnectMJ.bind('samoth','p1');send(player,{type:'state',state:{characterId:'samoth',hp:{current:60,max:72,temp:4},ac:15}});
 await until(()=>dom.window.eval('state.encounter.participants[0].hp')===60);
 let initiativeCommand=wait(player,'command');assert.equal(dom.window.RPGConnectMJ.prepareFight(),true);const request=(await initiativeCommand).event;assert.equal(request.type,'initiative:request');send(player,{type:'event',event:{id:'samoth-init-1',type:'initiative:rolled',characterId:'samoth',timestamp:new Date().toISOString(),payload:{requestId:request.payload.requestId,dice:[14],chosen:14,bonus:1,total:15,mode:'normal'}}});await until(()=>dom.window.document.querySelector('[data-fight-init="samoth"]')?.value==='15');assert.equal(dom.window.RPGConnectMJ.validateInitiative('samoth',15),true);assert.equal(dom.window.eval('state.encounter.participants[0].initiative'),15);assert.equal(dom.window.RPGConnectMJ.getStatus().fight.validated.samoth,true);send(player,{type:'command-ack',id:request.id,result:'applied'});
 let turnGrant=wait(player,'command');assert.equal(dom.window.RPGConnectMJ.startFight(),true);assert.equal((await turnGrant).event.type,'turn:grant');assert.equal(dom.window.eval('state.ui.mode'),'combat');
 let command=wait(player,'command');dom.window.eval("applyDamageMany(['p1'],8,'froid')");assert.equal((await command).event.payload.amount,8);
 assert.equal(dom.window.eval('localDamage'),0);assert.equal(dom.window.eval('state.encounter.participants[0].hp'),60);
 player.close();dom.window.RPGConnectMJ.getStatus();dom.window.close();
});
test.after(async()=>{for(const ws of wss.clients)ws.terminate();await new Promise(r=>server.close(r))});
